### ISSUE TITLE
infer

### ISSUE THREAD

**Issue by yanhan13944047669** [sithu31296/pose-estimation#3]
When I run infer.py, the following error occurs：
Traceback (most recent call last):
  File "D:/UserData/yanhan/RE-ID CO/pose-estimation-main/pose-estimation-main/infer.py", line 133, in <module>
    output = pose.predict(image)
  File "D:\Users\TEMP\.conda\envs\pytorch_gpu1\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "D:/UserData/yanhan/RE-ID CO/pose-estimation-main/pose-estimation-main/infer.py", line 102, in predict
    self.postprocess(pred, img, image)
  File "D:/UserData/yanhan/RE-ID CO/pose-estimation-main/pose-estimation-main/infer.py", line 96, in postprocess
    draw_keypoints(img0, coords, self.coco_skeletons)
  File "D:\UserData\yanhan\RE-ID CO\pose-estimation-main\pose-estimation-main\pose\utils\utils.py", line 37, in draw_keypoints
    cv2.line(img, kpts[kid1-1], kpts[kid2-1], (0, 255, 0), 2, cv2.LINE_AA)   
SystemError: new style getargs format but argument is not a tuple

What is the reason？
thanks.

**Comment by sithu31296** [comment]
I think it is an issue with opencv version. Please update your opencv version.

**Comment by yanhan13944047669** [comment]
> I think it is an issue with opencv version. Please update your opencv version.

After your guidance, I have successfully solved the problem.
thanks！
